#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
# yabai -m config                                 \
#     external_bar                 off:40:0       \
#     menubar_opacity              1.0            \
#     mouse_follows_focus          off            \
#     focus_follows_mouse          off            \
#     display_arrangement_order    default        \
#     window_origin_display        default        \
#     window_placement             second_child   \
#     window_zoom_persist          on             \
#     window_shadow                on             \
#     window_animation_duration    0.0            \
#     window_animation_easing      ease_out_circ  \
#     window_opacity_duration      0.0            \
#     active_window_opacity        1.0            \
#     normal_window_opacity        0.90           \
#     window_opacity               off            \
#     insert_feedback_color        0xffd75f5f     \
#     split_ratio                  0.50           \
#     split_type                   auto           \
#     auto_balance                 off            \
#     top_padding                  12             \
#     bottom_padding               12             \
#     left_padding                 12             \
#     right_padding                12             \
#     window_gap                   06             \
#     layout                       bsp            \
#     mouse_modifier               fn             \
#     mouse_action1                move           \
#     mouse_action2                resize         \
#     mouse_drop_action            swap

# echo "yabai configuration loaded.."

# window padding
yabai -m config top_padding 6
yabai -m config bottom_padding 6
yabai -m config left_padding 6
yabai -m config right_padding 6
yabai -m config window_gap 6

# 自動的にアクティブアクティブなウィンドウにフォーカスを合わせる
# https://github.com/koekeishiya/yabai/issues/485#issuecomment-617953545
function focus_under_cursor {
    if yabai -m query --windows --space |
        jq -er 'map(select(.focused == 1)) | length == 0' >/dev/null; then
        yabai -m window --focus mouse 2>/dev/null || true
    fi
}
yabai -m signal --add event=window_destroyed action="${functions[focus_under_cursor]}"
yabai -m signal --add event=window_minimized action="${functions[focus_under_cursor]}"
yabai -m signal --add event=application_hidden action="${functions[focus_under_cursor]}"

yabai -m signal --add event=window_focused action="$(chezmoi source-path)/_/yabai/window_focused"
$(chezmoi source-path)/_/yabai/border &
