#!/usr/bin/env sh

set -ex

xcode-select --install || echo "XCode already installed"

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(
    echo
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"'
) >>$HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install chezmoi
chezmoi init danielmschmidt
chezmoi init --apply akira-toriyama
