#!/usr/bin/env sh

# 再起動
# brew services restart yabai

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# 枠線
yabai -m config window_border on
yabai -m config window_border_width 4
~/dotfiles/script/yabai/border_color &

# ウィンドウのシャドウ
yabai -m config window_shadow off
