on:
  push:
  schedule:
    - cron: "* 10 * * *"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main

      - name: setup
        run: |
          ./script/setup.sh
        env:
          DOT_FILE_ROOT_PATH: /Users/runner/work/dotfiles
