on: 
  push:
  schedule:
    - cron: '* 10 * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup
      run: |
        ./script/macos/setup.sh
    